---
- include_tasks: check-swarm-mode.yml

- include_tasks: init-swarm-mode.yml

- include_tasks: worker-join-token.yml

- include_tasks: manager-join-token.yml

- include_tasks: set-swarm-manager-address.yml

- include_tasks: distribute-swarm-manager-address.yml

- include_tasks: join-workers.yml

- include_tasks: join-managers.yml
...