# Task to join workers to the swarm.
---
- name: Join the pending Swarm worker nodes.
  shell: docker swarm join
        --listen-addr "{{ private_ip }}:{{ docker_swarm_port }}"
        --advertise-addr "{{ private_ip }}:{{ docker_swarm_port }}"
        --token "{{ swarm_worker_token.stdout }}"
        "{{ swarm_manager_address }}"
  changed_when: false
  when: 
    - "docker_info.stdout.find('Swarm: active') == -1"
    - "docker_info.stdout.find('Swarm: pending') == -1"
    - "'worker_nodes' in group_names or 'db_worker_nodes' in group_names"
...
