# Task to leave swarm if in error state.
---
- name: "Leave swarm cluster if Swarm: error"
  shell: docker swarm leave --force
  changed_when: false
  when: 
    - "'Swarm: error' in docker_info.stdout"
...
