---
- name: Playbook for linux based systems.
  hosts: linux_servers
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - linux-docker
...