# This file contains the default values of variables of the ansible role.
# These can be overriden before the execution either with -e or --ext-vars options
# while running the ansible-playbooks that contain the this role.
---
glusterfs_daemon: glusterd

# For Ubuntu.
glusterfs_default_release: ""
glusterfs_ppa_use: true
glusterfs_ppa_version: "3.13"

# For Debian.
glusterfs_gpg_key_version: "3.13"
glusterfs_deb_version: "LATEST"
...