# Setp cloud controller based on the environment variables provided by jenkins.env.
# Setup command 'docker-compose up -d --build'
# Shutdown command 'docker-compose down'
# URL  http://<host_ip>:8888/
version: '3.2'

volumes:
  jenkins-home:
  svn_server:

services:
  jenkins:
    image: enactordev-on.azurecr.io/enactorbase/lin/jscdt:1.0.0
    env_file:
      - jenkins.env
    restart: unless-stopped
    ports:
      - target: 8080
        published: 8888
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-home:/var/jenkins_home
    links:
      - svn_server
    container_name: cloud_controller
  
  svn_server:
    image: enactordev-on.azurecr.io/enactorbase/lin/svn:1.0.0
    env_file:
      - jenkins.env
    restart: unless-stopped
    ports:
      - target: 80
        published: 7443
        protocol: tcp
        mode: host
    volumes:
      - svn_server:/home/svn
    container_name: svn_server
