#-------------------------------------------------------------------------------------------------
# This file is generated by terraform script builder grrovy script. Do not edit this file manualy
#-------------------------------------------------------------------------------------------------

#----------------------------------------
# Security Groups 
#----------------------------------------
module "sg-default" { # sg-group_identifier
  source = "./modules/security-group-default"
  resource_identifier = "${var.resource_identifier}"
  vpc_identifier = "${module.vpc.id}"
}

