# This file contains the default values of variables of the ansible role.
# These can be overriden before the execution either with -e or --ext-vars options
# while running the ansible-playbooks that contain the this role.
---
# Infrastructure boxes can use 2 types of OS images.
# 1. Normal images
# 2. CIS hardened images
# Configuring these 2 types is bit different to each other. Thus this variable is introduced.
# Values this variable could have: ['normal', 'cis-hardened']
node_config_mode: 'normal'

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_uninstall_first: false
docker_debian_version: "5:19.03.4~3-0" # docker-ce=5:19.03.4~3-0~ubuntu-bionic
docker_centos_version: "19.03.4-3.el7" # docker-ce-19.03.4-3.el7
docker_fedora_version: "19.03.4-3.fc31" # docker-ce-19.03.4-3.fc31
docker_debian_full_version: "{{ docker_package }}={{ docker_debian_version }}~{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}"
docker_redhat_full_version: "{{ docker_package }}-{{ (ansible_distribution == 'Fedora') | ternary(docker_fedora_version, docker_centos_version) }}"

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.23.2"
docker_compose_path: /usr/local/bin/docker-compose

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_arch: amd64
# ansible_distribution is the OS-distribution (e.g. CentOS, Ubuntu), ansible_distribution_release is the release of OS distribution (e.g. xenial, bionic)
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true

# Used only for RedHat/CentOS/Fedora. ternary - if true ? smthing : other
docker_yum_repo_url: "https://download.docker.com/linux/{{ (ansible_distribution == 'Fedora') | ternary('fedora','centos') }}/docker-{{ docker_edition }}.repo"
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0

# A list of users who will be added to the docker group.
docker_users:
  - "{{ ansible_user }}"

# Prerequisites python modules
install_python_modules: true
python_modules:
  - virtualenv
  - setuptools
  - docker
  - jsondiff
  - pyyaml 
  - httplib2
...
