---
- name: Playbook to setup docker for linux based bastion node.
  hosts:
    - bastion_nodes
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - linux-docker
    - install-cloud-controller
...
