---
all:
  children:
    manager_nodes:
      children:
        windows_servers:
          hosts:
            win-server-1:
              ansible_host: 192.168.1.35
              # By default 5986 is HTTPS where 5985 is HTTP. powershell "winrm enumerate winrm/config/Listener" will give the details.
              ansible_port: 5986   
              ansible_user: Administrator
              ansible_password: enactor@123
              ansible_connection: winrm
              # When using self-signed cert should ignore the certificate validation because it’s not going to be from a valid CA.
              ansible_winrm_server_cert_validation: ignore
        linux_servers:
          hosts:
            ubu-server-1:
              ansible_host: 192.168.1.9
              ansible_port: 22
              ansible_user: enactor
              ansible_ssh_private_key_file: "/home/thilinamad/.ssh/id_rsa"
              ansible_become_user: root
              ansible_become_pass: enactor  # TODO Instead of keepin plain-text use a vault here.

    worker_nodes:
      children:
        windows_servers:
          hosts:
            win-server-2:
              ansible_host: 192.168.1.35
              # By default 5986 is HTTPS where 5985 is HTTP. powershell "winrm enumerate winrm/config/Listener" will give the details.
              ansible_port: 5986   
              ansible_user: Administrator
              ansible_password: enactor@123
              ansible_connection: winrm
              # When using self-signed cert should ignore the certificate validation because it’s not going to be from a valid CA.
              ansible_winrm_server_cert_validation: ignore
        linux_servers:
          hosts:
            ubu-server-2:
              ansible_host: 192.168.1.9
              ansible_port: 22
              ansible_user: enactor
              ansible_ssh_private_key_file: "/home/thilinamad/.ssh/id_rsa"
              ansible_become_user: root
              ansible_become_pass: enactor  # TODO Instead of keepin plain-text use a vault here.

    db_worker_nodes:
      children:
        windows_servers:
          hosts:
            win-server-3:
              ansible_host: 192.168.1.35
              # By default 5986 is HTTPS where 5985 is HTTP. powershell "winrm enumerate winrm/config/Listener" will give the details.
              ansible_port: 5986   
              ansible_user: Administrator
              ansible_password: enactor@123
              ansible_connection: winrm
              # When using self-signed cert should ignore the certificate validation because it’s not going to be from a valid CA.
              ansible_winrm_server_cert_validation: ignore
        linux_servers:
          hosts:
            ubu-server-3:
              ansible_host: 192.168.1.9
              ansible_port: 22
              ansible_user: enactor
              ansible_ssh_private_key_file: "/home/thilinamad/.ssh/id_rsa"
              ansible_become_user: root
              ansible_become_pass: enactor  # TODO Instead of keepin plain-text use a vault here.
...
