---
- name: Join the pending Swarm manager nodes.
  shell: docker swarm join
        --listen-addr {{ ansible_host }}:{{ docker_swarm_port }}
        --advertise-addr {{ ansible_host }}
        --token "{{ swarm_manager_token.stdout }}"
        {{ swarm_manager_address }}
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1
    and docker_info.stdout.find('Swarm: pending') == -1
    and 'manager_nodes' in group_names
    and inventory_hostname != groups['manager_nodes'][0]"
...