---
- name: Make sure prerequisite unzip is installed on the machine.
  package: 
    name: unzip
    state: present
  become: true

- name: Creates the directory enactor-suite to unwrap deployment stack.
  file:
    path: "{{ deploy_suite_destination }}"
    state: directory

- name: Unzip the deployment stack to enactor-suite directory.
  unarchive:
    src: "{{ deploy_suite_zip_location }}"
    dest: "{{ deploy_suite_destination }}"
    remote_src: false
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
...