---
- name: Create secrets required for the  deployment stack.
  docker_secret:
    name: "{{ item['key'] }}"
    data: "{{ item['value'] }}"
    state: present
  with_items: "{{ docker_secrets }}"

- name: Log into docker registry and force re-authorization.
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    reauthorize: true

# docker_stack is only supported after ansible 2.8.
# - name: Deploy enactor application suite as docker stack.
#   docker_stack:
#     name: "{{ docker_stack_name }}" 
#     state: present
#     with_registry_auth: true
#     prune: true
#     compose:
#     - "{{ deploy_suite_destination }}/validation-stack.yml"

- name: Get the list of already deployed stacks.
  shell: docker stack ls
  register: docker_stack_list

- name: Deploy enactor application suite as docker stack.
  shell: docker stack deploy {{ docker_stack_name }}
         --compose-file {{ deploy_suite_destination }}/validation-stack.yml
         --with-registry-auth
         --prune
  when: "docker_stack_list.stdout.find(docker_stack_name) == -1"
...