---
version: "3.7"

networks:
  enactor-stack-overlay:
    name: enactor-stack-overlay

volumes:
  kibana-data:
    name: kibana-data

configs:
  kibana-config:
    file: ./envs/monitoring/kibana/kibana.yml

services:
  kibana:
    image: enactordev-on.azurecr.io/enactorbase/lin/kibana:2.6.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: []  
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 240s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        delay: 240s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    ports: 
      - target: 5601
        published: 5601
        mode: ingress
    networks:
      - enactor-stack-overlay
    volumes:
      - kibana-data:/usr/share/kibana/data
    configs:
      - source: kibana-config
        target: /usr/share/kibana/config/kibana.yml
        mode: 0555
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"
...
