---
version: '3.7'

networks:
  enactor-stack-overlay:
    name: enactor-stack-overlay

volumes:
  db-data-pp:
    external: true
    name: db-data-pp

secrets:
  allow_root_remote_login:
    file: ./resources/allow-root-remote-login.sql

services:
  mysql-pp:
    image: enactordev-on.azurecr.io/enactor-mysql:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: []
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    environment:
      - MYSQL_ROOT_PASSWORD=enactor
      - MYSQL_DATABASE=enactorpp
    ports:
      - target: 3306
        published: 3376
        mode: ingress
    networks:
      - enactor-stack-overlay
    volumes:
      - db-data-pp:/var/lib/mysql
    secrets:
      - source: allow_root_remote_login
        target: /docker-entrypoint-initdb.d/allow-root-remote-login.sql
        mode: 0555
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"
...