---
version: "3.7"

networks:
  enactor-stack-overlay:
    name: enactor-stack-overlay

configs:
  wazuh-config:
    file: ./envs/monitoring/wazuh/config/ossec.conf
  wazuh-filebeat-config:
    file: ./envs/monitoring/wazuh/wazuh-filebeat.yml

services: 
  wazuh:
    image: enactordev-on.azurecr.io/enactorbase/lin/wazuh:2.6.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: []
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 240s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        delay: 240s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    ports:
      - target: 55000
        published: 55000
        mode: ingress
      - target: 1514
        published: 1514
        protocol: udp
        mode: ingress
      - target: 1515
        published: 1515
        mode: ingress
      - target: 1516
        published: 1516
        mode: ingress
      - target: 514
        published: 514
        protocol: udp
        mode: ingress
    networks:
      - enactor-stack-overlay
    configs:
      - source: wazuh-config
        target: /etc/ossec.conf
        mode: 0555
      - source: wazuh-filebeat-config
        target: /etc/filebeat/filebeat.yml
        mode: 0555
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"
...