---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"

- name: Ensure docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-users.yml
  when: docker_users

- name: restart node to get the effect of docker install and user adding to docker group.
  reboot:

- include_tasks: docker-compose.yml
  when: docker_install_compose
...