---
version: '3.4'

networks:
  enactor-stack-overlay:
    external: 
      name: enactor-stack-overlay

volumes:
  enactor-data-oma-home:
    external: true
    name: enactor-data-oma-home

services:
  om-application:
    image: enactordev-on.azurecr.io/enactorstandard/win/oma:REPLACE_DOCKER_TAG
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: []  
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 240s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
    ports:
      - target: 39834
        published: 39834
        mode: host
      - target: 52244
        published: 52244
        mode: host
    networks:
      - enactor-stack-overlay                 
    env_file:
      - ./envs/common.env  
      - ./envs/common-om.env
      - ./envs/oma.env
    volumes:
      - enactor-data-oma-home:c:\enactor\app\home 
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"
...