---
version: '3.4'

networks:
  enactor-stack-overlay:
    external: 
      name: enactor-stack-overlay

services:
  wsm-server:
    image: enactordev-on.azurecr.io/enactorstandard/win/wsm:REPLACE_DOCKER_TAG  
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints: []  
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 240s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
    env_file:
      - ./envs/common.env
      - ./envs/wsm.env
    ports:
      - target: 39869
        published: 39869
        mode: host
      - target: 52279
        published: 52279
        mode: host
    networks:
      - enactor-stack-overlay 
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"
...