# Contains the tasks required to deploy enactor suite services.
---
- name: Create secrets required for the  deployment stack.
  docker_secret:
    name: "{{ item['key'] }}"
    data: "{{ item['value'] }}"
    state: present
  with_items: "{{ docker_secrets }}"

- name: Log into docker registry and force re-authorization.
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    reauthorize: true

# docker_stack is only supported after ansible 2.8.
# - name: Deploy enactor application suite as docker stack.
#   docker_stack:
#     name: "{{ docker_stack_name }}" 
#     state: present
#     with_registry_auth: true
#     prune: true
#     compose:
#     - "{{ deploy_suite_destination }}/validation-stack.yml"

- name: Get the list of already deployed stacks.
  shell: docker stack ls
  register: docker_stack_list

- name: Remove if stack already exists if remove_before_deploy is true.
  shell: docker stack rm {{ docker_stack_name }}
  register: docker_stack_remove
  when:
    - (remove_stack_before_deploy | bool)
    - "docker_stack_name in docker_stack_list.stdout"

- name: Pause for a while if stack removed.
  pause:
    seconds: 120
  when: "docker_stack_remove.changed"

- name: Get the list of already deployed stacks.
  shell: docker stack ls
  register: docker_stack_list

- include: network.yml
  when: 
    - (remove_stack_before_deploy | bool)

- include: orderly-deploy-services.yml
  with_items: "{{ services_to_deploy }}"
...
